language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - composer self-update

before_script:
    - composer install --no-interaction
    - mkdir -p build/logs

script:
    - phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
